name: Deno format & lint checker

on:
  workflow_call:

jobs:
  udd-check:
    runs-on: ubuntu-latest
    steps:
        - name: Show inputs
          run: |
            echo "configuration file is ${{ inputs.config_file }}"
        - uses: actions/checkout@v2
        - uses: denoland/setup-deno@v1
          with:
            deno-version: v1.x
        - name: Run fmt
          run: |
            deno fmt --check
        - name: Run lint
          run: |
            deno lint