name: Deno format & lint checker

on:
  workflow_call:
    inputs:
      config_file:
        required: false
        type: string

jobs:
  udd-check:
    runs-on: ubuntu-latest
    steps:
        - name: Show inputs
          run: |
            echo "deps file is ${{ inputs.config_file }}"
        - uses: actions/checkout@v2
        - uses: denoland/setup-deno@v1
          with:
            deno-version: v1.x
        - name: Run fmt
          run: |
            deno fmt -c ./deno.json --check
        - name: Run lint
          run: |
            deno lint -c ./deno.json