name: create-release

on:
  workflow_dispatch:
    inputs:
      version:
        type: string
        required: true
        description: 'Release version'

jobs:
  create-release:
    name: Create release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y/%m/%d')"
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          name: ${{ github.event.inputs.text }} - ${{ steps.date.outputs.date }}
          tag_name: ${{ github.event.inputs.version }}
          generate_release_notes: true
          files: deno.json